version: '3.8'
name: myproject 

services:
  bot:
    build: ./tgbot
    container_name: tgbot
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - default

networks:
  default:
    driver: bridge

